### ISSUE TITLE
[Feature]: 能否更新3.1版本的 play cover

### ISSUE THREAD

**Issue by grzzk** [hguandl/PlayCover#14]
### Is your feature request related to a problem?

最新的 3.1 版本 play cover 出来了。是否能同步更新下带 maa 的版本？

### Describe the solution you'd like

现版本连接手柄会卡顿飘移。

### Anything else?

感谢！

### Issue Language

- [X] Yes my issue is written in English

**Comment by hguandl** [comment]
不好意思没有留意这边的issue，已更新

**Comment by grzzk** [comment]
谢谢大佬更新.
