### ISSUE TITLE
[Bug]: 方舟没有网络连接（english version is translated by gpt)

### ISSUE THREAD

**Issue by lljgugugu** [hguandl/PlayCover#2]
### Describe the bug

目前方舟登陆模式正逐步更新，今天下午手(iphone se2)正常产生了登陆模式的变更，晚上打开playcover.maa.3.0.0.2发现持续不断的没有网络连接。

The Ark survival mode is currently being gradually updated. This afternoon, my iPhone SE2 experienced a normal change in the login mode. However, when I opened "playcover.maa.3.0.0.2" in the evening, I found that there was a continuous lack of network connectivity.

### Steps to reproduce

目前使用的是https://github.com/hguandl/PlayCover/releases 中[v3.0.0.maa.2](https://github.com/hguandl/PlayCover/releases/tag/v3.0.0.maa.2)，dmg包，
与https://decrypt.day/app/id1454663939中的砸壳，版本2.0.01，于北京时间2023年6.4日中午12时扔可以正常登录。

I am currently using the [v3.0.0.maa.2](https://github.com/hguandl/PlayCover/releases/tag/v3.0.0.maa.2) DMG package from https://github.com/hguandl/PlayCover/releases. It has been successfully paired with the cracking tool from https://decrypt.day/app/id1454663939, version 2.0.01. As of June 4th, 2023, at 12:00 PM Beijing time, I can still log in normally.

### Expected behaviour

希望能够定位问题是由于方舟登陆模式变更引起，还是其他未知原因。

I hope to determine whether the issue is caused by changes in the Ark login mode or other unknown reasons.

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by Rememorio** [comment]
相同的问题，直接原因似乎是方舟更新了登录界面的 UI

**Comment by lljgugugu** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by HongyuS** [comment]
该错误无限循环，且不显示错误代码
<img width="1220" alt="image" src="https://github.com/hguandl/PlayCover/assets/44023928/215a3ddb-e211-4402-a672-44cd700dd1b1">

**Comment by LinSHP** [comment]
相同的问题，同猜测是因为改变了登陆方式

**Comment by HaydenTtttya** [comment]
我也出现了这个问题🙋

**Comment by wzx1205** [comment]
同样无法启动

**Comment by tanuki-cat** [comment]
一样的问题应该是新ui 引起的

**Comment by baysonfox** [comment]
同样无法启动

**Comment by SainScarlet** [comment]
搬用的解决方案，亲测能用
原帖：
[https://discord.com/channels/871829896492642387/1115066956299644989/1115517758310989884](url)

```
cd ~/Library/Containers/io.playcover.PlayCover/明日方舟.app/Frameworks/HGSDK.framework
cp HGSDK HGSDK.bak
perl -i -pe 's|(\^\[\^\\.\]\+\\.hypergryph\\.com\$)|substr($1,0,-2)."n\$"|eg' HGSDK
codesign -fs- HGSDK
```

<img width="566" alt="image" src="https://github.com/hguandl/PlayCover/assets/101003874/5e5a72e4-a4ad-488d-975b-f4f237fbd9fe">
<img width="499" alt="image" src="https://github.com/hguandl/PlayCover/assets/101003874/42a7fc8e-15d1-40aa-94f7-aa68250783a8">

**Comment by lljgugugu** [comment]
感谢您的分享，亲测可用，虽然原理还没看懂，正式关闭此issue

**Comment by RekiDunois** [comment]
> 搬用的解决方案，亲测能用 原帖： [https://discord.com/channels/871829896492642387/1115066956299644989/1115517758310989884](url)
> 
> ```
> cd ~/Library/Containers/io.playcover.PlayCover/明日方舟.app/Frameworks/HGSDK.framework
> cp HGSDK HGSDK.bak
> perl -i -pe 's|(\^\[\^\\.\]\+\\.hypergryph\\.com\$)|substr($1,0,-2)."n\$"|eg' HGSDK
> codesign -fs- HGSDK
> ```
> 
> <img alt="image" width="566" src="https://private-user-images.githubusercontent.com/101003874/243880097-5e5a72e4-a4ad-488d-975b-f4f237fbd9fe.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Njk1ODA0NTIsIm5iZiI6MTc2OTU4MDE1MiwicGF0aCI6Ii8xMDEwMDM4NzQvMjQzODgwMDk3LTVlNWE3MmU0LWE0YWQtNDg4ZC05NzViLWY0ZjIzN2ZiZDlmZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDEyOFQwNjAyMzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOTA1NTUzNjkxODlmZmY1MzExZjlmZDRlODA0ODc5YzMyNWY5NzU4MDgyMDBlYzk3NzNjNzdkYTJhYzMwZTI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.2ZKSLftagGLoSpe16hMfAe_YHd8fbyf2JnZlKwDvh7M"> <img alt="image" width="499" src="https://private-user-images.githubusercontent.com/101003874/243880365-42a7fc8e-15d1-40aa-94f7-aa68250783a8.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Njk1ODA0NTIsIm5iZiI6MTc2OTU4MDE1MiwicGF0aCI6Ii8xMDEwMDM4NzQvMjQzODgwMzY1LTQyYTdmYzhlLTE1ZDEtNDBhYS05NGY3LWFhNjgyNTA3ODNhOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDEyOFQwNjAyMzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZDVmYzBhZWY2MzkwMjhhNmI0NzBlZjQ0MWYyOTRjNDY1NDQ1ZGRmMmNlZDRjOTgyMjllZGUxYzllYjg1NDMwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.lDbzU8s-KUKOQxfprjVFkRoXwLRNha__GJEdhTePxcI">

这个方法里的`HGSDK.framework`路径好像不见了

**Comment by lljgugugu** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
