### ISSUE TITLE
[Feature]: 希望仓库能与上游playcover:develop同步

### ISSUE THREAD

**Issue by Cold-sand** [hguandl/PlayCover#8]
### Is your feature request related to a problem?

虽然现在的的版本可以顺利的运行明日方舟和使用MAATools，但我想运行些别的IOS游戏，运行这些游戏只能使用官网最新每日构建，但是使用官方构建无法使用MAATools。

### Describe the solution you'd like

与上游仓库同步

### Anything else?

NO

### Issue Language

- [X] Yes my issue is written in English

**Comment by pzee** [comment]
> ### Is your feature request related to a problem?
> 虽然现在的的版本可以顺利的运行明日方舟和使用MAATools，但我想运行些别的IOS游戏，运行这些游戏只能使用官网最新每日构建，但是使用官方构建无法使用MAATools。
> 
> ### Describe the solution you'd like
> 与上游仓库同步
> 
> ### Anything else?
> NO
> 
> ### Issue Language
> * [x]  Yes my issue is written in English

我同步了上游代码，需要的话，可以下载使用看看 https://github.com/pzee/PlayCover/releases
